INSERT INTO tb_genero (id, nome) VALUES (1, 'Ação');
INSERT INTO tb_genero (id, nome) VALUES (2, 'Aventura');
INSERT INTO tb_genero (id, nome) VALUES (3, 'Comédia');
INSERT INTO tb_genero (id, nome) VALUES (4, 'Drama');
INSERT INTO tb_genero (id, nome) VALUES (5, 'Ficção Científica');
INSERT INTO tb_genero (id, nome) VALUES (6, 'Conto');
INSERT INTO tb_genero (id, nome) VALUES (7, 'Romance');
INSERT INTO tb_genero (id, nome) VALUES (8, 'Suspense');
INSERT INTO tb_genero (id, nome) VALUES (9, 'Terror');
INSERT INTO tb_genero (id, nome) VALUES (10, 'Literatura Estrangeira');
INSERT INTO tb_genero (id, nome) VALUES (11, 'Literatura Nacional');
INSERT INTO tb_genero (id, nome) VALUES (12, 'Biografia');
INSERT INTO tb_genero (id, nome) VALUES (13, 'História');
INSERT INTO tb_genero (id, nome) VALUES (14, 'Policial');
INSERT INTO tb_genero (id, nome) VALUES (15, 'Fantasia');
INSERT INTO tb_genero (id, nome) VALUES (16, 'Infantil');
INSERT INTO tb_genero (id, nome) VALUES (17, 'Autoajuda');
INSERT INTO tb_genero (id, nome) VALUES (18, 'Ficção');
INSERT INTO tb_genero (id, nome) VALUES (19, 'Arte');
INSERT INTO tb_genero (id, nome) VALUES (20, 'Filosofia');
INSERT INTO tb_genero (id, nome) VALUES (21, 'Teconologia');
INSERT INTO tb_genero (id, nome) VALUES (22, 'Infantojuvenil');
INSERT INTO tb_genero (id, nome) VALUES (23, 'Crime');